### ISSUE TITLE
Can you please share the code for the training processedure?

### ISSUE THREAD

**Issue by fbiying87** [alldbi/FLM#3]
Thanks for sharing your source code. It helps a lot to get your proposed idea.

I was wondering, if you can also provide the code for the training processedure? The current version works well for CASIA-Web Images, but I was wondering, if I can train it on another database. 

Thanks a lot. 

Have a nice day!

Best Regards!

**Comment by alldbi** [comment]
Hi, 

I am glad that you are interested in our work. Our attack model is independent of the training model. So, we mainly used trained deep face recognition models from available repositories. Hence, you can also use any model on repositories and use it as a target model in our algorithm. 

Thanks, 
Ali

**Comment by fbiying87** [comment]
Thx for replying so quickly. 

So the current class output is 10575 due to CASIA database. If I would use LFW, how should I adapt the y label. The output is also different from 10575. Can you give me a hint? 

So I should change the number of output class and retrain it to store the correct model weights based on Facenet. Do you have some sample codes on that? 

Thanks for your help!

Best!

**Comment by PPPPPPPeng** [comment]
> Thx for replying so quickly.
> 
> So the current class output is 10575 due to CASIA database. If I would use LFW, how should I adapt the y label. The output is also different from 10575. Can you give me a hint?
> 
> So I should change the number of output class and retrain it to store the correct model weights based on Facenet. Do you have some sample codes on that?
> 
> Thanks for your help!
> 
> Best!

Have you solve this problem?
